### PR TITLE
Feature/add lazy loading for images

### LINKED ISSUE #36: Add Lazy loading to Images
## Use case
The Images are getting fetched from an API. This sometimes takes a while to fetch all the images and they may start to behave improperly.

## Proposal
We need to add lazy loading for images to load images properly when necessary. 

### Would you like to work on this issue?
No.

### PR DESCRIPTION
**Pull request by davidfranquet**
Fixes #36 

**Summary**: 

- Added a new Widget called LazyImage to handle the lazy loading for images
- Added golden test for the new widget

**Before**
Oct-18-2019 09-53-20

**After**
Oct-18-2019 09-56-42

### CODE REVIEW

**Comment by AyushBherwani1998** [comment]
Hey @DavidFD005 
Thanks for the PR. Can you please follow the PR Template and attach the screenshot of before and after to get better insights.

**Comment by davidfranquet** [comment]
> Hey @DavidFD005
> Thanks for the PR. Can you please follow the PR Template and attach the screenshot of before and after to get better insights.

Sure

**Comment by davidfranquet** [comment]
> Hey @DavidFD005
> Thanks for the PR. Can you please follow the PR Template and attach the screenshot of before and after to get better insights.

Added GIFs

**Review by AyushBherwani1998 — APPROVED** [review]

**Comment by AyushBherwani1998** [comment]
> 
> 
> > Hey @DavidFD005
> > Thanks for the PR. Can you please follow the PR Template and attach the screenshot of before and after to get better insights.
> 
> Added GIFs

Looks Great.
Thank you

**Pull request merged**
